#!/usr/bin/env python3
"""Generate oracles_tables_<game>.c from a WLA-DX symbol file of oracles-disasm.

The decoders never carry a ROM address in their source: every table address
comes from ages.sym / seasons.sym through this generator, so a change of the
pinned disasm commit is a regeneration, not an edit.

usage: gen_tables.py --sym PATH --game ages|seasons [--out DIR]
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

LABELS = [
    "roomLayoutGroupTable", "tilesetData", "tilesetLayoutTable", "tilesetLayoutDictionaryTable",
    "tileMappingTable", "tileMappingIndexDataPointer", "tileMappingAttributeDataPointer",
    "gfxHeaderTable", "uniqueGfxHeadersStart", "roomTilesetsGroupTable", "paletteHeaderTable",
    "animationGroupTable", "animationGfxHeaders", "objectGfxHeaderTable",
    # A mod's composition: the tables it rewrites, and the parser whose bank the object streams share.
    "warpSourcesTable", "warpDestTable", "objectDataGroupTable", "musicAssignmentGroupTable", "parseObjectData",
]

# Counts declared as assembler defines in the data files, not present in the symbol file.
COUNTS = {
    "ages": {"num_gfx_headers": 0xbb, "num_unique_gfx_headers": 0x15, "num_palette_headers": 0xcb,
             "num_tileset_layouts": 64},
    "seasons": {"num_gfx_headers": 0xbb, "num_unique_gfx_headers": 0x29, "num_palette_headers": 0xbe,
                "num_tileset_layouts": 64},
}


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def load_labels(path: Path) -> dict[str, tuple[int, int]]:
    labels: dict[str, tuple[int, int]] = {}
    in_labels = False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("["):
            in_labels = line.strip() == "[labels]"
            continue
        if in_labels:
            m = re.match(r"^([0-9a-f]{2}):([0-9a-f]{4}) (\S+)$", line.strip())
            if m:
                labels.setdefault(m.group(3), (int(m.group(1), 16), int(m.group(2), 16)))
    return labels


def section_ends(path: Path) -> dict[int, int]:
    """The CPU address where the last section of each ROM bank ends, from the [sections] map."""
    ends: dict[int, int] = {}
    in_sections = False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("["):
            in_sections = line.strip() == "[sections]"
            continue
        m = re.match(r"^[0-9a-f]{8} ([0-9a-f]{2}):[0-9a-f]{4} ([0-9a-f]{4}) ([0-9a-f]{8}) \S+$", line.strip()) if in_sections else None
        if m:
            bank, end = int(m.group(1), 16), int(m.group(2), 16) + int(m.group(3), 16)
            ends[bank] = max(ends.get(bank, 0), end)
    return ends


# The free tails a mod's composition writes in: after the last section of the warp lists' bank and of the
# object streams' bank; what follows a section there is fill or garbage no code reads (ROM_DATA_FORMATS, section 15).
FREE_TAILS = [("warp_bank_free", "warpSourcesTable"), ("object_bank_free", "parseObjectData")]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sym", type=Path, required=True)
    ap.add_argument("--game", choices=("ages", "seasons"), required=True)
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parent)
    args = ap.parse_args()
    labels = load_labels(args.sym)
    lines = [f"/* Generated by gen_tables.py from {args.sym.name}; do not edit. */",
             '#include "oracles_rom.h"', "",
             f"const OraclesTables oracles_tables_{args.game} = {{"]
    for name in LABELS:
        if name not in labels:
            raise SystemExit(f"missing symbol {name} in {args.sym}")
        bank, addr = labels[name]
        lines.append(f"    .{snake(name)} = {{ 0x{bank:02x}, 0x{addr:04x} }},")
    ends = section_ends(args.sym)
    for field, anchor in FREE_TAILS:
        bank = labels[anchor][0]
        if not 0x4000 <= ends.get(bank, 0) <= 0x8000:
            raise SystemExit(f"no section end in bank {bank:02x} of {args.sym}")
        lines.append(f"    .{field} = {{ 0x{bank:02x}, 0x{ends[bank]:04x} }},")
    for key, value in COUNTS[args.game].items():
        lines.append(f"    .{key} = {value},")
    lines += ["};", ""]
    out = args.out / f"oracles_tables_{args.game}.c"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
