/* The window's icon (launcher/icon/window_icon.c, generated by tools/make_icons.py): 64 x 64 pixels in RGBA, the
 * icon's rounded square opaque at its centre and transparent at its corners. */
#include "window_icon.h"

#include <stdio.h>

static int failures;
#define CHECK(condition) do { if (!(condition)) { failures++; fprintf(stderr, "FAIL %s:%d %s\n", __FILE__, __LINE__, #condition); } } while (0)

static unsigned alpha(unsigned x, unsigned y) { return oracles_window_icon[(y * ORACLES_WINDOW_ICON_SIZE + x) * 4u + 3u]; }

int main(void)
{
    CHECK(ORACLES_WINDOW_ICON_SIZE == 64);
    CHECK(sizeof oracles_window_icon == 64u * 64u * 4u);
    CHECK(alpha(32, 32) == 255 && alpha(2, 32) == 255 && alpha(32, 61) == 255);
    CHECK(alpha(0, 0) == 0 && alpha(63, 0) == 0 && alpha(0, 63) == 0 && alpha(63, 63) == 0);
    if (failures) { fprintf(stderr, "%d failure(s)\n", failures); return 1; }
    printf("launcher icon: the window's icon is 64 x 64 RGBA, opaque inside its rounded square\n");
    return 0;
}
