#!/usr/bin/env python3
"""Embed SameBoy's free CGB boot ROM as C (cgb_boot_rom.c, cgb_boot_rom.h).

usage: gen_boot_rom.py PATH/TO/cgb_boot.bin

The binary comes from a SameBoy build (build/bin/BootROMs/cgb_boot.bin) of
the version pinned in config/sameboy.json. Its SHA-256 is written into the C
file so that the embedded bytes can be checked against a fresh build.
"""
from __future__ import annotations

import hashlib
import pathlib
import sys


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    data = pathlib.Path(sys.argv[1]).read_bytes()
    sha = hashlib.sha256(data).hexdigest()
    here = pathlib.Path(__file__).resolve().parent
    lines = [
        "/* SameBoy 1.0.3 free CGB boot ROM (BootROMs/cgb_boot.asm), built once with RGBDS",
        " * and embedded so that no assembler is needed to build the engine.",
        " * Licence: Expat (MIT), see ../third_party/sameboy/LICENSE.",
        f" * SHA-256 of the {len(data)} bytes: {sha}",
        " * Generated by gen_boot_rom.py; do not edit. */",
        '#include "cgb_boot_rom.h"',
        "",
        f"const size_t oracles_cgb_boot_rom_size = {len(data)};",
        "const unsigned char oracles_cgb_boot_rom[] = {",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{x:02x}" for x in data[i:i + 16]) + ",")
    lines += ["};", ""]
    (here / "cgb_boot_rom.c").write_text("\n".join(lines), encoding="utf-8")
    (here / "cgb_boot_rom.h").write_text(
        "#ifndef ORACLES_CGB_BOOT_ROM_H\n#define ORACLES_CGB_BOOT_ROM_H\n\n#include <stddef.h>\n\n"
        "/* SameBoy's free CGB boot ROM, embedded; cgb_boot_rom.c carries its SHA-256. */\n"
        "extern const unsigned char oracles_cgb_boot_rom[];\nextern const size_t oracles_cgb_boot_rom_size;\n\n#endif\n",
        encoding="utf-8")
    print(f"{len(data)} bytes, sha256 {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
