# Build step, run by CMake itself (cmake -P), so that it runs on the building
# machine whatever the target, Android's included: writes a C file holding the
# launcher's fonts and motifs as byte arrays, so that the binary needs no asset
# beside it (the Windows build ships the-oracles-project.exe with its DLLs and the
# licences, nothing else).  Each array ends with a NUL byte that is not counted
# in its size, so that a text asset is also a C string.
#
#   cmake -DOUT=OUT.c "-DASSETS=NAME=PATH|NAME=PATH|..." -P ui_embed.cmake

if(NOT OUT OR NOT ASSETS)
    message(FATAL_ERROR "usage: cmake -DOUT=OUT.c -DASSETS=NAME=PATH|... -P ui_embed.cmake")
endif()
string(REPLACE "|" ";" ASSETS "${ASSETS}")
list(REMOVE_ITEM ASSETS "")

# 32 bytes a line: the pattern of one line, and of one byte.
set(byte "0x[0-9a-f][0-9a-f],")
string(REPEAT "${byte}" 32 line)

set(text "/* Generated by launcher/ui/ui_embed.cmake; do not edit. */\n#include \"ui_assets.h\"\n\n")
set(table "")
set(index 0)
foreach(asset IN LISTS ASSETS)
    string(FIND "${asset}" "=" equals)
    string(SUBSTRING "${asset}" 0 ${equals} name)
    math(EXPR start "${equals} + 1")
    string(SUBSTRING "${asset}" ${start} -1 path)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "ui_embed: cannot open ${path}")
    endif()
    file(SIZE "${path}" size)
    file(READ "${path}" hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "${line}" "\\0\n" bytes "${bytes}")
    string(APPEND text "static const unsigned char asset_${index}[] = {\n${bytes}0\n};\n")
    string(APPEND table "    { \"${name}\", asset_${index}, ${size} },\n")
    math(EXPR index "${index} + 1")
endforeach()
string(APPEND text "\nconst OraclesUiAsset oracles_ui_assets[] = {\n${table}};\nconst unsigned oracles_ui_asset_count = ${index};\n")
file(WRITE "${OUT}" "${text}")
