/* Generated by tools/make_icons.py from launcher/icon/source/mark-medium.svg; do not edit. */
#ifndef ORACLES_WINDOW_ICON_H
#define ORACLES_WINDOW_ICON_H

#define ORACLES_WINDOW_ICON_SIZE 64

/* The application's icon for the window, ORACLES_WINDOW_ICON_SIZE pixels square, RGBA, rows from the top. */
extern const unsigned char oracles_window_icon[ORACLES_WINDOW_ICON_SIZE * ORACLES_WINDOW_ICON_SIZE * 4];

#endif
